{{- if not .Values.tele.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kbot.secretName" . }}
  labels:
    {{- include "kbot.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.tele.secretKey }}: {{ .Values.tele.token | b64enc | quote }}
{{- end }}
