apiVersion: v2
name: kbot
description: Helm chart for kbot - Telegram bot written in Go (GlobalLogic DEVOPS101, Module 6, GitOps)
type: application

# Версія чарту
version: 1.1.0

# Версія застосунку (тег образу за замовчуванням)
appVersion: "v1.0.0"

home: https://github.com/Alexander-2212/kbot
sources:
  - https://github.com/Alexander-2212/kbot
keywords:
  - telegram
  - bot
  - golang
maintainers:
  - name: Alexander-2212
